title: What is entropy?
hero_image: images/banner.png
description: Find out what entropy is and how it can be improved
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Step one
